### ISSUE TITLE
HTTP Server for Latest Resource Status

### ISSUE THREAD

**Issue by jessecarl** [lazyengineering/faststatus#15]
Implement an HTTP service for resources.
* [x] Issue #5 New Resources
* [x] Issue #4 Read Status
* [x] Issue #2 Set Status

Resources are not currently planned to be deletable. Some form of inactivity purge may be implemented in the future, but for now, there is not a strong enough use case for deleting a resource.
